name = "lapor-kursus"
compatibility_date = "2026-06-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "lapor-kursus-db"
database_id = "6ba5540e-473d-4928-b0db-547c3cf82e2c"
